insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!248!',q'!AALAND ISLANDS!',q'!AX!',q'!ALA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!4!',q'!AFGHANISTAN!',q'!AF!',q'!AFG!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!8!',q'!ALBANIA!',q'!AL!',q'!ALB!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!12!',q'!ALGERIA!',q'!DZ!',q'!DZA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!16!',q'!AMERICAN SAMOA!',q'!AS!',q'!ASM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!20!',q'!ANDORRA!',q'!AD!',q'!AND!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!24!',q'!ANGOLA!',q'!AO!',q'!AGO!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!660!',q'!ANGUILLA!',q'!AI!',q'!AIA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!10!',q'!ANTARCTICA!',q'!AQ!',q'!ATA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!28!',q'!ANTIGUA AND BARBUDA!',q'!AG!',q'!ATG!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!32!',q'!ARGENTINA!',q'!AR!',q'!ARG!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!51!',q'!ARMENIA!',q'!AM!',q'!ARM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!533!',q'!ARUBA!',q'!AW!',q'!ABW!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!36!',q'!AUSTRALIA!',q'!AU!',q'!AUS!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!40!',q'!AUSTRIA!',q'!AT!',q'!AUT!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!31!',q'!AZERBAIJAN!',q'!AZ!',q'!AZE!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!44!',q'!BAHAMAS!',q'!BS!',q'!BHS!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!48!',q'!BAHRAIN!',q'!BH!',q'!BHR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!50!',q'!BANGLADESH!',q'!BD!',q'!BGD!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!52!',q'!BARBADOS!',q'!BB!',q'!BRB!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!112!',q'!BELARUS!',q'!BY!',q'!BLR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!56!',q'!BELGIUM!',q'!BE!',q'!BEL!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!84!',q'!BELIZE!',q'!BZ!',q'!BLZ!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!204!',q'!BENIN!',q'!BJ!',q'!BEN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!60!',q'!BERMUDA!',q'!BM!',q'!BMU!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!64!',q'!BHUTAN!',q'!BT!',q'!BTN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!68!',q'!BOLIVIA!',q'!BO!',q'!BOL!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!70!',q'!BOSNIA AND HERZEGOWINA!',q'!BA!',q'!BIH!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!72!',q'!BOTSWANA!',q'!BW!',q'!BWA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!74!',q'!BOUVET ISLAND!',q'!BV!',q'!BVT!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!76!',q'!BRAZIL!',q'!BR!',q'!BRA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!86!',q'!BRITISH INDIAN OCEAN TERRITORY!',q'!IO!',q'!IOT!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!96!',q'!BRUNEI DARUSSALAM!',q'!BN!',q'!BRN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!100!',q'!BULGARIA!',q'!BG!',q'!BGR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!854!',q'!BURKINA FASO!',q'!BF!',q'!BFA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!108!',q'!BURUNDI!',q'!BI!',q'!BDI!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!116!',q'!CAMBODIA!',q'!KH!',q'!KHM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!120!',q'!CAMEROON!',q'!CM!',q'!CMR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!124!',q'!CANADA!',q'!CA!',q'!CAN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!132!',q'!CAPE VERDE!',q'!CV!',q'!CPV!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!136!',q'!CAYMAN ISLANDS!',q'!KY!',q'!CYM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!140!',q'!CENTRAL AFRICAN REPUBLIC!',q'!CF!',q'!CAF!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!148!',q'!CHAD!',q'!TD!',q'!TCD!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!152!',q'!CHILE!',q'!CL!',q'!CHL!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!156!',q'!CHINA!',q'!CN!',q'!CHN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!162!',q'!CHRISTMAS ISLAND!',q'!CX!',q'!CXR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!166!',q'!COCOS (KEELING) ISLANDS!',q'!CC!',q'!CCK!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!170!',q'!COLOMBIA!',q'!CO!',q'!COL!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!174!',q'!COMOROS!',q'!KM!',q'!COM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!180!',q'!CONGO, Democratic Republic of (was Zaire)!',q'!CD!',q'!COD!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!178!',q'!CONGO, Republic of!',q'!CG!',q'!COG!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!184!',q'!COOK ISLANDS!',q'!CK!',q'!COK!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!188!',q'!COSTA RICA!',q'!CR!',q'!CRI!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!384!',q'!COTE D'IVOIRE!',q'!CI!',q'!CIV!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!191!',q'!CROATIA (local name: Hrvatska)!',q'!HR!',q'!HRV!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!192!',q'!CUBA!',q'!CU!',q'!CUB!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!196!',q'!CYPRUS!',q'!CY!',q'!CYP!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!203!',q'!CZECH REPUBLIC!',q'!CZ!',q'!CZE!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!208!',q'!DENMARK!',q'!DK!',q'!DNK!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!262!',q'!DJIBOUTI!',q'!DJ!',q'!DJI!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!212!',q'!DOMINICA!',q'!DM!',q'!DMA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!214!',q'!DOMINICAN REPUBLIC!',q'!DO!',q'!DOM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!218!',q'!ECUADOR!',q'!EC!',q'!ECU!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!818!',q'!EGYPT!',q'!EG!',q'!EGY!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!222!',q'!EL SALVADOR!',q'!SV!',q'!SLV!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!226!',q'!EQUATORIAL GUINEA!',q'!GQ!',q'!GNQ!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!232!',q'!ERITREA!',q'!ER!',q'!ERI!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!233!',q'!ESTONIA!',q'!EE!',q'!EST!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!231!',q'!ETHIOPIA!',q'!ET!',q'!ETH!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!238!',q'!FALKLAND ISLANDS (MALVINAS)!',q'!FK!',q'!FLK!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!234!',q'!FAROE ISLANDS!',q'!FO!',q'!FRO!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!242!',q'!FIJI!',q'!FJ!',q'!FJI!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!246!',q'!FINLAND!',q'!FI!',q'!FIN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!250!',q'!FRANCE!',q'!FR!',q'!FRA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!254!',q'!FRENCH GUIANA!',q'!GF!',q'!GUF!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!258!',q'!FRENCH POLYNESIA!',q'!PF!',q'!PYF!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!260!',q'!FRENCH SOUTHERN TERRITORIES!',q'!TF!',q'!ATF!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!266!',q'!GABON!',q'!GA!',q'!GAB!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!270!',q'!GAMBIA!',q'!GM!',q'!GMB!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!268!',q'!GEORGIA!',q'!GE!',q'!GEO!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!276!',q'!GERMANY!',q'!DE!',q'!DEU!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!288!',q'!GHANA!',q'!GH!',q'!GHA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!292!',q'!GIBRALTAR!',q'!GI!',q'!GIB!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!300!',q'!GREECE!',q'!GR!',q'!GRC!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!304!',q'!GREENLAND!',q'!GL!',q'!GRL!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!308!',q'!GRENADA!',q'!GD!',q'!GRD!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!312!',q'!GUADELOUPE!',q'!GP!',q'!GLP!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!316!',q'!GUAM!',q'!GU!',q'!GUM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!320!',q'!GUATEMALA!',q'!GT!',q'!GTM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!324!',q'!GUINEA!',q'!GN!',q'!GIN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!624!',q'!GUINEA-BISSAU!',q'!GW!',q'!GNB!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!328!',q'!GUYANA!',q'!GY!',q'!GUY!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!332!',q'!HAITI!',q'!HT!',q'!HTI!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!334!',q'!HEARD AND MC DONALD ISLANDS!',q'!HM!',q'!HMD!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!340!',q'!HONDURAS!',q'!HN!',q'!HND!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!344!',q'!HONG KONG!',q'!HK!',q'!HKG!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!348!',q'!HUNGARY!',q'!HU!',q'!HUN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!352!',q'!ICELAND!',q'!IS!',q'!ISL!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!356!',q'!INDIA!',q'!IN!',q'!IND!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!360!',q'!INDONESIA!',q'!ID!',q'!IDN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!364!',q'!IRAN (ISLAMIC REPUBLIC OF)!',q'!IR!',q'!IRN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!368!',q'!IRAQ!',q'!IQ!',q'!IRQ!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!372!',q'!IRELAND!',q'!IE!',q'!IRL!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!376!',q'!ISRAEL!',q'!IL!',q'!ISR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!380!',q'!ITALY!',q'!IT!',q'!ITA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!388!',q'!JAMAICA!',q'!JM!',q'!JAM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!392!',q'!JAPAN!',q'!JP!',q'!JPN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!400!',q'!JORDAN!',q'!JO!',q'!JOR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!398!',q'!KAZAKHSTAN!',q'!KZ!',q'!KAZ!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!404!',q'!KENYA!',q'!KE!',q'!KEN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!296!',q'!KIRIBATI!',q'!KI!',q'!KIR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!408!',q'!KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF!',q'!KP!',q'!PRK!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!410!',q'!KOREA, REPUBLIC OF!',q'!KR!',q'!KOR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!414!',q'!KUWAIT!',q'!KW!',q'!KWT!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!417!',q'!KYRGYZSTAN!',q'!KG!',q'!KGZ!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!418!',q'!LAO PEOPLE'S DEMOCRATIC REPUBLIC!',q'!LA!',q'!LAO!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!428!',q'!LATVIA!',q'!LV!',q'!LVA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!422!',q'!LEBANON!',q'!LB!',q'!LBN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!426!',q'!LESOTHO!',q'!LS!',q'!LSO!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!430!',q'!LIBERIA!',q'!LR!',q'!LBR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!434!',q'!LIBYAN ARAB JAMAHIRIYA!',q'!LY!',q'!LBY!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!438!',q'!LIECHTENSTEIN!',q'!LI!',q'!LIE!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!440!',q'!LITHUANIA!',q'!LT!',q'!LTU!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!442!',q'!LUXEMBOURG!',q'!LU!',q'!LUX!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!446!',q'!MACAU!',q'!MO!',q'!MAC!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!807!',q'!MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF!',q'!MK!',q'!MKD!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!450!',q'!MADAGASCAR!',q'!MG!',q'!MDG!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!454!',q'!MALAWI!',q'!MW!',q'!MWI!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!458!',q'!MALAYSIA!',q'!MY!',q'!MYS!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!462!',q'!MALDIVES!',q'!MV!',q'!MDV!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!466!',q'!MALI!',q'!ML!',q'!MLI!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!470!',q'!MALTA!',q'!MT!',q'!MLT!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!584!',q'!MARSHALL ISLANDS!',q'!MH!',q'!MHL!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!474!',q'!MARTINIQUE!',q'!MQ!',q'!MTQ!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!478!',q'!MAURITANIA!',q'!MR!',q'!MRT!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!480!',q'!MAURITIUS!',q'!MU!',q'!MUS!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!175!',q'!MAYOTTE!',q'!YT!',q'!MYT!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!484!',q'!MEXICO!',q'!MX!',q'!MEX!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!583!',q'!MICRONESIA, FEDERATED STATES OF!',q'!FM!',q'!FSM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!498!',q'!MOLDOVA, REPUBLIC OF!',q'!MD!',q'!MDA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!492!',q'!MONACO!',q'!MC!',q'!MCO!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!496!',q'!MONGOLIA!',q'!MN!',q'!MNG!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!500!',q'!MONTSERRAT!',q'!MS!',q'!MSR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!504!',q'!MOROCCO!',q'!MA!',q'!MAR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!508!',q'!MOZAMBIQUE!',q'!MZ!',q'!MOZ!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!104!',q'!MYANMAR!',q'!MM!',q'!MMR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!516!',q'!NAMIBIA!',q'!NA!',q'!NAM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!520!',q'!NAURU!',q'!NR!',q'!NRU!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!524!',q'!NEPAL!',q'!NP!',q'!NPL!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!528!',q'!NETHERLANDS!',q'!NL!',q'!NLD!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!530!',q'!NETHERLANDS ANTILLES!',q'!AN!',q'!ANT!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!540!',q'!NEW CALEDONIA!',q'!NC!',q'!NCL!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!554!',q'!NEW ZEALAND!',q'!NZ!',q'!NZL!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!558!',q'!NICARAGUA!',q'!NI!',q'!NIC!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!562!',q'!NIGER!',q'!NE!',q'!NER!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!566!',q'!NIGERIA!',q'!NG!',q'!NGA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!570!',q'!NIUE!',q'!NU!',q'!NIU!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!574!',q'!NORFOLK ISLAND!',q'!NF!',q'!NFK!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!580!',q'!NORTHERN MARIANA ISLANDS!',q'!MP!',q'!MNP!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!578!',q'!NORWAY!',q'!NO!',q'!NOR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!512!',q'!OMAN!',q'!OM!',q'!OMN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!586!',q'!PAKISTAN!',q'!PK!',q'!PAK!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!585!',q'!PALAU!',q'!PW!',q'!PLW!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!275!',q'!PALESTINIAN TERRITORY, Occupied!',q'!PS!',q'!PSE!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!591!',q'!PANAMA!',q'!PA!',q'!PAN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!598!',q'!PAPUA NEW GUINEA!',q'!PG!',q'!PNG!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!600!',q'!PARAGUAY!',q'!PY!',q'!PRY!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!604!',q'!PERU!',q'!PE!',q'!PER!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!608!',q'!PHILIPPINES!',q'!PH!',q'!PHL!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!612!',q'!PITCAIRN!',q'!PN!',q'!PCN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!616!',q'!POLAND!',q'!PL!',q'!POL!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!620!',q'!PORTUGAL!',q'!PT!',q'!PRT!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!630!',q'!PUERTO RICO!',q'!PR!',q'!PRI!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!634!',q'!QATAR!',q'!QA!',q'!QAT!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!638!',q'!REUNION!',q'!RE!',q'!REU!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!642!',q'!ROMANIA!',q'!RO!',q'!ROU!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!643!',q'!RUSSIAN FEDERATION!',q'!RU!',q'!RUS!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!646!',q'!RWANDA!',q'!RW!',q'!RWA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!654!',q'!SAINT HELENA!',q'!SH!',q'!SHN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!659!',q'!SAINT KITTS AND NEVIS!',q'!KN!',q'!KNA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!662!',q'!SAINT LUCIA!',q'!LC!',q'!LCA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!666!',q'!SAINT PIERRE AND MIQUELON!',q'!PM!',q'!SPM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!670!',q'!SAINT VINCENT AND THE GRENADINES!',q'!VC!',q'!VCT!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!882!',q'!SAMOA!',q'!WS!',q'!WSM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!674!',q'!SAN MARINO!',q'!SM!',q'!SMR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!678!',q'!SAO TOME AND PRINCIPE!',q'!ST!',q'!STP!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!682!',q'!SAUDI ARABIA!',q'!SA!',q'!SAU!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!686!',q'!SENEGAL!',q'!SN!',q'!SEN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!891!',q'!SERBIA AND MONTENEGRO!',q'!CS!',q'!SCG!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!690!',q'!SEYCHELLES!',q'!SC!',q'!SYC!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!694!',q'!SIERRA LEONE!',q'!SL!',q'!SLE!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!702!',q'!SINGAPORE!',q'!SG!',q'!SGP!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!703!',q'!SLOVAKIA!',q'!SK!',q'!SVK!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!705!',q'!SLOVENIA!',q'!SI!',q'!SVN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!90!',q'!SOLOMON ISLANDS!',q'!SB!',q'!SLB!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!706!',q'!SOMALIA!',q'!SO!',q'!SOM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!710!',q'!SOUTH AFRICA!',q'!ZA!',q'!ZAF!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!239!',q'!SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS!',q'!GS!',q'!SGS!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!724!',q'!SPAIN!',q'!ES!',q'!ESP!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!144!',q'!SRI LANKA!',q'!LK!',q'!LKA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!736!',q'!SUDAN!',q'!SD!',q'!SDN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!740!',q'!SURINAME!',q'!SR!',q'!SUR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!744!',q'!SVALBARD AND JAN MAYEN ISLANDS!',q'!SJ!',q'!SJM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!748!',q'!SWAZILAND!',q'!SZ!',q'!SWZ!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!752!',q'!SWEDEN!',q'!SE!',q'!SWE!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!756!',q'!SWITZERLAND!',q'!CH!',q'!CHE!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!760!',q'!SYRIAN ARAB REPUBLIC!',q'!SY!',q'!SYR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!158!',q'!TAIWAN!',q'!TW!',q'!TWN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!762!',q'!TAJIKISTAN!',q'!TJ!',q'!TJK!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!834!',q'!TANZANIA, UNITED REPUBLIC OF!',q'!TZ!',q'!TZA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!764!',q'!THAILAND!',q'!TH!',q'!THA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!626!',q'!TIMOR-LESTE!',q'!TL!',q'!TLS!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!768!',q'!TOGO!',q'!TG!',q'!TGO!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!772!',q'!TOKELAU!',q'!TK!',q'!TKL!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!776!',q'!TONGA!',q'!TO!',q'!TON!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!780!',q'!TRINIDAD AND TOBAGO!',q'!TT!',q'!TTO!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!788!',q'!TUNISIA!',q'!TN!',q'!TUN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!792!',q'!TURKEY!',q'!TR!',q'!TUR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!795!',q'!TURKMENISTAN!',q'!TM!',q'!TKM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!796!',q'!TURKS AND CAICOS ISLANDS!',q'!TC!',q'!TCA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!798!',q'!TUVALU!',q'!TV!',q'!TUV!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!800!',q'!UGANDA!',q'!UG!',q'!UGA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!804!',q'!UKRAINE!',q'!UA!',q'!UKR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!784!',q'!UNITED ARAB EMIRATES!',q'!AE!',q'!ARE!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!826!',q'!UNITED KINGDOM!',q'!GB!',q'!GBR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!840!',q'!UNITED STATES!',q'!US!',q'!USA!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!581!',q'!UNITED STATES MINOR OUTLYING ISLANDS!',q'!UM!',q'!UMI!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!858!',q'!URUGUAY!',q'!UY!',q'!URY!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!860!',q'!UZBEKISTAN!',q'!UZ!',q'!UZB!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!548!',q'!VANUATU!',q'!VU!',q'!VUT!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!336!',q'!VATICAN CITY STATE (HOLY SEE)!',q'!VA!',q'!VAT!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!862!',q'!VENEZUELA!',q'!VE!',q'!VEN!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!704!',q'!VIET NAM!',q'!VN!',q'!VNM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!92!',q'!VIRGIN ISLANDS (BRITISH)!',q'!VG!',q'!VGB!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!850!',q'!VIRGIN ISLANDS (U.S.)!',q'!VI!',q'!VIR!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!876!',q'!WALLIS AND FUTUNA ISLANDS!',q'!WF!',q'!WLF!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!732!',q'!WESTERN SAHARA!',q'!EH!',q'!ESH!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!887!',q'!YEMEN!',q'!YE!',q'!YEM!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!894!',q'!ZAMBIA!',q'!ZM!',q'!ZMB!');
insert into T_country (countryId, countryName, isoCountryCodeA2, isoCountryCodeA2) values (q'!716!',q'!ZIMBABWE!',q'!ZW!',q'!ZWE!');
