insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!AB!',q'!Alba!',642,q'!Alba Iulia!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!AR!',q'!Arad!',642,q'!Arad!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!AG!',q'!Arge?!',642,q'!Pite?ti!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!BC!',q'!Bac?u!',642,q'!Bac?u!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!BH!',q'!Bihor!',642,q'!Oradea!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!BN!',q'!Bistri?a-N?s?ud!',642,q'!Bistri?a!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!BT!',q'!Boto?ani!',642,q'!Boto?ani!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!BR!',q'!Br?ila!',642,q'!Br?ila!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!BV!',q'!Bra?ov!',642,q'!Bra?ov!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!B!',q'!Bucharest!',642,q'!Bucharest!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!BZ!',q'!Buz?u!',642,q'!Buz?u!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!CL!',q'!C?l?ra?i!',642,q'!C?l?ra?i!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!CS!',q'!Cara?-Severin!',642,q'!Re?i?a!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!CJ!',q'!Cluj!',642,q'!Cluj-Napoca!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!CT!',q'!Constan?a!',642,q'!Constan?a!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!CV!',q'!Covasna!',642,q'!Sfântu Gheorghe!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!DB!',q'!Dâmbovi?a!',642,q'!Târgovi?te!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!DJ!',q'!Dolj!',642,q'!Craiova!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!GL!',q'!Gala?i!',642,q'!Gala?i!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!GR!',q'!Giurgiu!',642,q'!Giurgiu!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!GJ!',q'!Gorj!',642,q'!Târgu Jiu!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!HR!',q'!Harghita!',642,q'!Miercurea-Ciuc!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!HD!',q'!Hunedoara!',642,q'!Deva!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!IL!',q'!Ialomi?a!',642,q'!Slobozia!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!IS!',q'!Ia?i!',642,q'!Ia?i!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!IF!',q'!Ilfov!',642,q'!Bucharest!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!MM!',q'!Maramure?!',642,q'!Baia Mare!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!MH!',q'!Mehedin?i!',642,q'!Drobeta-Turnu Severin!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!MS!',q'!Mure?!',642,q'!Târgu Mure?!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!NT!',q'!Neam?!',642,q'!Piatra-Neam?!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!OT!',q'!Olt!',642,q'!Slatina!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!PH!',q'!Prahova!',642,q'!Ploie?ti!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!SJ!',q'!S?laj!',642,q'!Zal?u!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!SM!',q'!Satu Mare!',642,q'!Satu Mare!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!SB!',q'!Sibiu!',642,q'!Sibiu!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!SV!',q'!Suceava!',642,q'!Suceava!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!TR!',q'!Teleorman!',642,q'!Alexandria!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!TM!',q'!Timi?!',642,q'!Timi?oara!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!TL!',q'!Tulcea!',642,q'!Tulcea!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!VL!',q'!Vâlcea!',642,q'!Râmnicu Vâlcea!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!VS!',q'!Vaslui!',642,q'!Vaslui!');
insert into T_county (countyId, countyName, countryId, countyCapital) values (q'!VN!',q'!Vrancea!',642,q'!Foc?ani!');
