insert into T_departments(departmentId,departmentName,departmentNameAlt) values (0,q'!All departments!',q'!Toate departamentele!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (3,q'!Insurance!',q'!Asigurari!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (4,q'!Real Estate !',q'!Imobiliare!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (5,q'!Sales!',q'!Vanzari!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (7,q'!Legal!',q'!Juridic!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (8,q'!Human resources !',q'!Resurse umane / Psihologie!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (9,q'!Public relations !',q'!Relatii publice!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (10,q'!Office / Back-office / Secretarial!',q'!Office / Back-office / Secretariat!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (12,q'!Marketing!',q'!Marketing!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (14,q'!Other !',q'!Altele!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (15,q'!Human medicine!',q'!Medicina umana!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (16,q'!Pharmaceutical!',q'!Farmacie!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (17,q'!Construction / Facilities !',q'!Constructii / Instalatii!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (18,q'!Architecture / Interior design !',q'!Arhitectura / Design interior!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (20,q'!Advertising !',q'!Publicitate!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (22,q'!Graphics / Web design / DTP!',q'!Grafica / Webdesign / DTP!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (23,q'!Education / Training / Arta!',q'!Educatie / Training / Arte!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (24,q'!Administrative / Logistics!',q'!Administrativ / Logistica!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (25,q'!Agriculture!',q'!Agricultura!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (26,q'!Security / Military!',q'!Paza si protectie / Militar!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (28,q'!NGO / Volunteering!',q'!ONG / Voluntariat!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (29,q'!Public office!',q'!Functii publice!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (30,q'!Tourism / Hotel staff!',q'!Turism / Hotel staff!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (31,q'!Internet / e-Commerce!',q'!Internet / e-Commerce!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (36,q'!Manufacturing !',q'!Productie!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (38,q'!Telecommunications !',q'!Telecomunicatii!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (39,q'!Research & development !',q'!Cercetare - dezvoltare!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (40,q'!Transportation / Distribution!',q'!Transport / Distributie!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (41,q'!Procurement!',q'!Achizitii!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (42,q'!Printing / Publishing!',q'!Tipografii / Edituri!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (44,q'!Client Service / Call Center!',q'!Relatii clienti / Call center!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (45,q'!Engineering !',q'!Inginerie!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (46,q'!Statistics / Mathematics!',q'!Statistica / Matematica!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (47,q'!International trading!',q'!Import - export!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (48,q'!Environmental Protection!',q'!Protectia mediului!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (49,q'!Chemistry / Biotech!',q'!Chimie / Biochimie!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (50,q'!Labor Protection!',q'!Protectia muncii!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (51,q'!Wood Industry!',q'!Prelucrarea lemnului / PVC!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (52,q'!Au pair / Babysitter / Cleaning!',q'!Au pair / Babysitter / Curatenie!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (53,q'!Merchandising !',q'!Merchandising / Promoteri!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (54,q'!Quality Control !',q'!Controlul calitatii!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (55,q'!Translations !',q'!Traduceri!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (56,q'!Oil / Gas!',q'!Petrol / Gaze!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (57,q'!IT Software !',q'!IT Software!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (58,q'!IT Hardware !',q'!IT Hardware!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (59,q'!Finance / Accounting!',q'!Financiar / Contabilitate!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (60,q'!Banks !',q'!Banci!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (61,q'!Crewing / Casino / Entertainment!',q'!Crewing / Casino / Entertainment!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (62,q'!Sport / Wellness!',q'!Sport / Wellness!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (63,q'!Alternative Medicine !',q'!Medicina alternativa!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (64,q'!Beauty Salons !',q'!Saloane / Clinici frumusete!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (65,q'!Textile / Fashion design!',q'!Confectii / Design vestimentar!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (66,q'!Alimentation!',q'!Alimentatie / HoReCa!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (67,q'!Automotive / Equipment !',q'!Auto / Echipamente!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (68,q'!Civil engineering / Industrial design !',q'!Proiectare civila / industriala!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (69,q'!Service / Maintenance!',q'!Service / Reparatii!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (70,q'!MLM / Direct Sales!',q'!MLM / Vanzari directe!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (71,q'!Audit / Consulting!',q'!Audit / Consultanta!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (72,q'!Naval / Aeronautical!',q'!Naval / Aeronautic!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (101,q'!Management!',q'!Management!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (102,q'!Veterinary medicine!',q'!Medicina veterinara!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (103,q'!Qualified personnel!',q'!Personal calificat!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (104,q'!Journalism / Editorial!',q'!Jurnalism / Editorial!');
insert into T_departments(departmentId,departmentName,departmentNameAlt) values (105,q'!Specialists / Technicians!',q'!Specialisti / Tehnicieni!');
