insert into T_departments(departmentId,departmentName) values (0,q'!All departments!');
insert into T_departments(departmentId,departmentName) values (24,q'!Administrative / Logistics!');
insert into T_departments(departmentId,departmentName) values (20,q'!Advertising !');
insert into T_departments(departmentId,departmentName) values (25,q'!Agriculture!');
insert into T_departments(departmentId,departmentName) values (66,q'!Alimentation!');
insert into T_departments(departmentId,departmentName) values (63,q'!Alternative Medicine !');
insert into T_departments(departmentId,departmentName) values (18,q'!Architecture / Interior design !');
insert into T_departments(departmentId,departmentName) values (52,q'!Au pair / Babysitter / Cleaning!');
insert into T_departments(departmentId,departmentName) values (71,q'!Audit / Consulting!');
insert into T_departments(departmentId,departmentName) values (67,q'!Automotive / Equipment !');
insert into T_departments(departmentId,departmentName) values (60,q'!Banks !');
insert into T_departments(departmentId,departmentName) values (64,q'!Beauty Salons !');
insert into T_departments(departmentId,departmentName) values (49,q'!Chemistry / Biotech!');
insert into T_departments(departmentId,departmentName) values (68,q'!Civil engineering / Industrial design !');
insert into T_departments(departmentId,departmentName) values (44,q'!Client Service / Call Center!');
insert into T_departments(departmentId,departmentName) values (17,q'!Construction / Facilities !');
insert into T_departments(departmentId,departmentName) values (61,q'!Crewing / Casino / Entertainment!');
insert into T_departments(departmentId,departmentName) values (23,q'!Education / Training / Arta!');
insert into T_departments(departmentId,departmentName) values (45,q'!Engineering !');
insert into T_departments(departmentId,departmentName) values (48,q'!Environmental Protection!');
insert into T_departments(departmentId,departmentName) values (59,q'!Finance / Accounting!');
insert into T_departments(departmentId,departmentName) values (22,q'!Graphics / Web design / DTP!');
insert into T_departments(departmentId,departmentName) values (15,q'!Human medicine!');
insert into T_departments(departmentId,departmentName) values (8,q'!Human resources !');
insert into T_departments(departmentId,departmentName) values (3,q'!Insurance!');
insert into T_departments(departmentId,departmentName) values (47,q'!International trading!');
insert into T_departments(departmentId,departmentName) values (31,q'!Internet / e-Commerce!');
insert into T_departments(departmentId,departmentName) values (58,q'!IT Hardware !');
insert into T_departments(departmentId,departmentName) values (57,q'!IT Software !');
insert into T_departments(departmentId,departmentName) values (104,q'!Journalism / Editorial!');
insert into T_departments(departmentId,departmentName) values (50,q'!Labor Protection!');
insert into T_departments(departmentId,departmentName) values (7,q'!Legal!');
insert into T_departments(departmentId,departmentName) values (101,q'!Management!');
insert into T_departments(departmentId,departmentName) values (36,q'!Manufacturing !');
insert into T_departments(departmentId,departmentName) values (12,q'!Marketing!');
insert into T_departments(departmentId,departmentName) values (53,q'!Merchandising !');
insert into T_departments(departmentId,departmentName) values (70,q'!MLM / Direct Sales!');
insert into T_departments(departmentId,departmentName) values (72,q'!Naval / Aeronautical!');
insert into T_departments(departmentId,departmentName) values (28,q'!NGO / Volunteering!');
insert into T_departments(departmentId,departmentName) values (10,q'!Office / Back-office / Secretarial!');
insert into T_departments(departmentId,departmentName) values (56,q'!Oil / Gas!');
insert into T_departments(departmentId,departmentName) values (14,q'!Other !');
insert into T_departments(departmentId,departmentName) values (16,q'!Pharmaceutical!');
insert into T_departments(departmentId,departmentName) values (42,q'!Printing / Publishing!');
insert into T_departments(departmentId,departmentName) values (41,q'!Procurement!');
insert into T_departments(departmentId,departmentName) values (29,q'!Public office!');
insert into T_departments(departmentId,departmentName) values (9,q'!Public relations !');
insert into T_departments(departmentId,departmentName) values (103,q'!Qualified personnel!');
insert into T_departments(departmentId,departmentName) values (54,q'!Quality Control !');
insert into T_departments(departmentId,departmentName) values (4,q'!Real Estate !');
insert into T_departments(departmentId,departmentName) values (39,q'!Research & development !');
insert into T_departments(departmentId,departmentName) values (5,q'!Sales!');
insert into T_departments(departmentId,departmentName) values (26,q'!Security / Military!');
insert into T_departments(departmentId,departmentName) values (69,q'!Service / Maintenance!');
insert into T_departments(departmentId,departmentName) values (105,q'!Specialists / Technicians!');
insert into T_departments(departmentId,departmentName) values (62,q'!Sport / Wellness!');
insert into T_departments(departmentId,departmentName) values (46,q'!Statistics / Mathematics!');
insert into T_departments(departmentId,departmentName) values (38,q'!Telecommunications !');
insert into T_departments(departmentId,departmentName) values (65,q'!Textile / Fashion design!');
insert into T_departments(departmentId,departmentName) values (30,q'!Tourism / Hotel staff!');
insert into T_departments(departmentId,departmentName) values (55,q'!Translations !');
insert into T_departments(departmentId,departmentName) values (40,q'!Transportation / Distribution!');
insert into T_departments(departmentId,departmentName) values (102,q'!Veterinary medicine!');
insert into T_departments(departmentId,departmentName) values (51,q'!Wood Industry!');
