insert into T_industry (industryId,industryName,industryNameAlt) values (0,q'!All industries!',q'!Toate industriile!');
insert into T_industry (industryId,industryName,industryNameAlt) values (1,q'!Administrative / Public Sector!',q'!Administratie / Sector Public!');
insert into T_industry (industryId,industryName,industryNameAlt) values (2,q'!Agriculture!',q'!Agrara!');
insert into T_industry (industryId,industryName,industryNameAlt) values (3,q'!Arts / Entertainment!',q'!Arta / Entertainment!');
insert into T_industry (industryId,industryName,industryNameAlt) values (4,q'!Insurance!',q'!Asigurari!');
insert into T_industry (industryId,industryName,industryNameAlt) values (5,q'!Financial / Banking!',q'!Banci / Servicii financiare!');
insert into T_industry (industryId,industryName,industryNameAlt) values (6,q'!Call-Center / BPO!',q'!Call-center / BPO!');
insert into T_industry (industryId,industryName,industryNameAlt) values (7,q'!Chemistry!',q'!Chimica!');
insert into T_industry (industryId,industryName,industryNameAlt) values (8,q'!Commerce / Retail!',q'!Comert / Retail!');
insert into T_industry (industryId,industryName,industryNameAlt) values (9,q'!Construction!',q'!Constructi!');
insert into T_industry (industryId,industryName,industryNameAlt) values (10,q'!Education / Training!',q'!Educatie / Training!');
insert into T_industry (industryId,industryName,industryNameAlt) values (11,q'!Pharma!',q'!Farma!');
insert into T_industry (industryId,industryName,industryNameAlt) values (12,q'!Real estate!',q'!Imobiliara!');
insert into T_industry (industryId,industryName,industryNameAlt) values (13,q'!Food and Drinks!',q'!Alimentara!');
insert into T_industry (industryId,industryName,industryNameAlt) values (14,q'!Auto / Automotive!',q'!Masini / Auto!');
insert into T_industry (industryId,industryName,industryNameAlt) values (15,q'!Wood / PVC!',q'!Lemn / PVC!');
insert into T_industry (industryId,industryName,industryNameAlt) values (16,q'!Naval / Aeronautical!',q'!Navala / Aeronautica!');
insert into T_industry (industryId,industryName,industryNameAlt) values (17,q'!Textile!',q'!Textila!');
insert into T_industry (industryId,industryName,industryNameAlt) values (18,q'!IT / Telecom!',q'!IT / Telecom!');
insert into T_industry (industryId,industryName,industryNameAlt) values (19,q'!Media / Internet!',q'!Media / Internet!');
insert into T_industry (industryId,industryName,industryNameAlt) values (20,q'!Medicine / Health!',q'!Medicina / Sanatate!');
insert into T_industry (industryId,industryName,industryNameAlt) values (21,q'!Security!',q'!Paza si protectie!');
insert into T_industry (industryId,industryName,industryNameAlt) values (22,q'!Oil / Gas!',q'!Petrol / Gaze!');
insert into T_industry (industryId,industryName,industryNameAlt) values (23,q'!Services!',q'!Prestari servicii!');
insert into T_industry (industryId,industryName,industryNameAlt) values (24,q'!Environmental Protection!',q'!Protectia mediului!');
insert into T_industry (industryId,industryName,industryNameAlt) values (25,q'!Advertising / Marketing / PR!',q'!Publicitate / Marketing / PR!');
insert into T_industry (industryId,industryName,industryNameAlt) values (26,q'!Sport / Beauty / Spa!',q'!Sport / Frumusete!');
insert into T_industry (industryId,industryName,industryNameAlt) values (27,q'!Transport / Logistics / Import - Export!',q'!Transport / Logistica / Import - Export!');
insert into T_industry (industryId,industryName,industryNameAlt) values (28,q'!Tourism!',q'!Turism / HoReCa!');
insert into T_industry (industryId,industryName,industryNameAlt) values (29,q'!Law!',q'!Drept!');
insert into T_industry (industryId,industryName,industryNameAlt) values (30,q'!Energy!',q'!Energetica!');
