insert into T_industry (industryId,industryName,industryNameAlt) values (0,q'!All industries!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (1,q'!Administrative / Public Sector!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (25,q'!Advertising / Marketing / PR!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (2,q'!Agriculture!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (3,q'!Arts / Entertainment!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (14,q'!Auto / Automotive!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (6,q'!Call-Center / BPO!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (7,q'!Chemistry!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (8,q'!Commerce / Retail!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (9,q'!Construction!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (10,q'!Education / Training!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (30,q'!Energy!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (24,q'!Environmental Protection!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (5,q'!Financial / Banking!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (13,q'!Food and Drinks!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (4,q'!Insurance!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (18,q'!IT / Telecom!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (29,q'!Law!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (19,q'!Media / Internet!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (20,q'!Medicine / Health!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (16,q'!Naval / Aeronautical!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (22,q'!Oil / Gas!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (11,q'!Pharma!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (12,q'!Real estate!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (21,q'!Security!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (23,q'!Services!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (26,q'!Sport / Beauty / Spa!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (17,q'!Textile!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (28,q'!Tourism!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (27,q'!Transport / Logistics / Import - Export!',q'!!');
insert into T_industry (industryId,industryName,industryNameAlt) values (15,q'!Wood / PVC!',q'!!');
